# Generated by Django 6.0.2 on 2026-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_refresh_interval', models.IntegerField(default=120, help_text='Seconds between automatic fetches')),
                ('high_alert_threshold', models.IntegerField(default=11)),
                ('alert_threshold', models.IntegerField(default=8)),
                ('rate_limit', models.IntegerField(default=3, help_text='Max concurrent requests / per-second window')),
                ('max_orders', models.IntegerField(blank=True, default=10, help_text='Max orders to show per item; blank for no limit', null=True)),
            ],
            options={
                'verbose_name': 'Market Settings',
                'verbose_name_plural': 'Market Settings',
            },
        ),
    ]
