# Generated by Django 6.0.2 on 2026-04-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('item_ids', models.JSONField(default=list)),
                ('source_balances', models.JSONField(default=list)),
                ('rate_limit', models.IntegerField(default=1)),
                ('max_orders', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('aborted', 'Aborted')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FetchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=16)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('market_data', models.JSONField(default=list)),
                ('failed_items', models.JSONField(default=list)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('successful_items', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.OneToOneField(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='progress_record', to='market.fetchjob', to_field='session_id')),
            ],
        ),
    ]
