# Generated by Django 6.0.2 on 2026-04-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_fetchjob_fetchprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchprogress',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='FetchJob',
        ),
        migrations.DeleteModel(
            name='FetchProgress',
        ),
    ]
