# Generated by Django 5.2.4 on 2025-08-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, unique=True)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
