# Generated by Django 6.0.2 on 2026-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_price'),
        ('sources', '0002_rename_source_sourcebalance_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='items', to='sources.sourcebalance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
