# Generated by Django 6.0.2 on 2026-02-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_sources_alter_item_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
    ]
