# Generated by Django 5.1.7 on 2025-08-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, unique=True)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
