# Generated by Django 6.0.2 on 2026-02-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcebalance',
            old_name='source',
            new_name='source_name',
        ),
    ]
